version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: go get github.com/stretchr/testify
      - run: go get -u github.com/jstemmer/go-junit-report

      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -v | tee ${TEST_RESULTS}/go-test.out


      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - store_test_results:
          path: /tmp/test-results
